configure: make the SPIR-V header flags depend on vulkan
The SPIR-V header probe runs while vulkan is still auto-enabled, before
check_deps has a chance to disable it for a missing dependency such as
threads.

This fixes builds without threads, which would fail to link:

  error: undefined symbol: backend_spirv
  referenced by ops.c:42 (libswscale/ops.c:42)

Fixes: 2b6fbcad6d

Signed-off-by: Kacper Michajłow <kasper93@gmail.com>